# -*- coding: utf-8 -*-
"""MyNotebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TYOhq636xXpHoq1zf_1-kcdOyWsZ9Vx4
"""

print('Hello World!')